version: '3'
services:
  web:
    container_name: httpd1
    ports:
      - "8081:80"
    image: apache:latest
    networks:
      - net-test
  web2:
    container_name: httpd2
    ports:
      - "8082:80"
    image: apache:latest
    networks:
      - net-test
networks:
  net-test: