version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    env_file:
      - common.env
    #environment:
      #- "MYSQL_ROOT_PASSWORD=123456789"